[package]
name = "query_executor"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
ast = { path = "../ast" }
binary = { path = "../binary" }
constraints = { path = "../constraints" }
data_manager = { path = "../data_manager" }
expr_eval = { path = "../expr_eval" }
kernel = { path = "../kernel" }
plan = { path = "../plan" }
protocol = { path = "../protocol" }
sql_model = { path = "../sql_model" }

bigdecimal = "0.1.2"
futures-lite = "1.7.0"
log = "0.4.11"
sqlparser = { version = "0.6.1", features = ["bigdecimal"] }

[dev-dependencies]
rstest = "0.6.4"
tempfile = "3.1.0"
