[package]
name = "protocol"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4.8"
itertools = "0.9.0"
futures-lite = "0.1.11"
byteorder = "1.3.4"
async-trait = "0.1.37"
async-dup = "1.2.1"
async-net = "0.1.2"
async-native-tls = "0.3.3"
blocking = "0.5.2"
async-mutex = "1.1.5"

[dev-dependencies]
tempfile = "3.1.0"
