[package]
name = "protocol"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4.11"
itertools = "0.9.0"
futures-lite = "1.2.0"
byteorder = "1.3.4"
async-trait = "0.1.40"
async-dup = "1.2.1"
async-native-tls = "0.3.3"
blocking = "1.0.0"
async-mutex = "1.3.0"

[dev-dependencies]
tempfile = "3.1.0"
