[package]
name = "protocol"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4.8"
async-trait = "0.1.35"
itertools = "0.9.0"
futures = "0.3.5"
byteorder = "1.0"
bytes = "0.5"

[dev-dependencies]
async-std = { version = "1.6.0", features = ["attributes"] }
test_helpers = { path = "../test_helpers" }
