[package]
name = "protocol"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
async-dup = "1.2.2"
async-mutex = "1.3.0"
#TODO temporal to have ability to run ./local/code_coverage.sh
async-native-tls = { git = "https://github.com/alex-dukhno/async-native-tls.git", branch = "new-native-tls" }
async-trait = "0.1.40"
blocking = "1.0.0"
byteorder = "1.3.4"
futures-lite = "1.7.0"
itertools = "0.9.0"
log = "0.4.11"

[dev-dependencies]
tempfile = "3.1.0"
