[package]
name = "data_manager"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
kernel = { path = "../kernel" }
log = "0.4.11"
sled = { version = "0.34.3", features = ["default"] }
sql_types = { path = "../sql_types" }
serde = { version = "1.0.115", features = ["derive"] }
bincode = "1.3.1"
representation = { path = "../representation" }
itertools = "0.9.0"
fail = { version = "0.4.0", features = ["failpoints"] }

[dev-dependencies]
backtrace = "0.3.50"
rstest = "0.6.4"
tempfile = "3.1.0"

[[test]]
name = "sled_fails_to_open_db"
path = "tests/failpoints/open_db.rs"
required-features = ["fail/failpoints"]

[[test]]
name = "sled_fails_to_open_tree"
path = "tests/failpoints/open_tree.rs"
required-features = ["fail/failpoints"]

[[test]]
name = "sled_fails_to_drop_db"
path = "tests/failpoints/drop_db.rs"
required-features = ["fail/failpoints"]

[[test]]
name = "sled_fails_to_drop_tree"
path = "tests/failpoints/drop_tree.rs"
required-features = ["fail/failpoints"]

[[test]]
name = "sled_fails_to_insert_into_tree"
path = "tests/failpoints/insert_into_tree.rs"
required-features = ["fail/failpoints"]

[[test]]
name = "sled_fails_to_flush_tree"
path = "tests/failpoints/flush_tree.rs"
required-features = ["fail/failpoints"]

[[test]]
name = "sled_fails_to_iterate_over_tree"
path = "tests/failpoints/iterate_over_tree.rs"
required-features = ["fail/failpoints"]

[[test]]
name = "sled_fails_to_remove_from_tree"
path = "tests/failpoints/remove_from_tree.rs"
required-features = ["fail/failpoints"]
