[package]
name = "sql_engine"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
ast = { path = "../ast" }
log = "0.4.11"
kernel = { path = "../kernel" }
data_manager = { path = "../data_manager" }
sqlparser = { version = "0.6.1", features = ["bigdecimal"] }
bigdecimal = "0.1.2"
sql_model = { path = "../sql_model" }
query_planner = { path = "../query_planner" }
protocol = { path = "../protocol" }
futures-lite = "1.4.0"
representation = { path = "../binary" }
bincode = "1.3.1"
itertools = "0.9.0"

[dev-dependencies]
rstest = "0.6.4"
tempfile = "3.1.0"
