[package]
name = "sql_engine"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4.8"
kernel = { path = "../kernel" }
storage = { path = "../storage" }
sqlparser = "0.5.1"
sql_types = { path = "../sql_types" }

[dev-dependencies]
rstest = "0.6.4"
test_helpers = { path = "../test_helpers" }
