[package]
name = "binder"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
pg_wire = "0.1.0"

log = "0.4.11"
sqlparser = { git = "https://github.com/ballista-compute/sqlparser-rs.git", branch = "main", features = ["bigdecimal"] }

[dev-dependencies]
bigdecimal = { version = "0.2.0", features = ["string-only"] }
rstest = "0.6.4"
