[package]
name = "representation"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4.8"
sql_types = { path = "../sql_types" }
ordered-float = "2.0.0"
sqlparser = { version = "0.6.1", features = ["bigdecimal"] }
bigdecimal = "0.1.2"
