[package]
name = "catalog"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
data_definition_execution_plan = { path = "../data_definition/execution_plan" }
binary = { path = "../../data_repr/binary" }
definition = { path = "../../definition" }
storage = { path = "../../storage/" }
types = { path = "../../types" }

dashmap = "4.0.2"
log = "0.4.14"

[dev-dependencies]
rstest = "0.7.0"
