[package]
name = "node"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[lib]
name = "node"

[[bin]]
name = "database"
path = "src/bin.rs"

[dependencies]
binder = { path = "../binder" }
data_manager = { path = "../data_manager" }
kernel = { path = "../kernel" }
parser = { path = "../parser" }
plan = { path = "../plan" }
protocol = { path = "../protocol" }
query_executor = { path = "../query_executor" }
query_planner = { path = "../query_planner" }
sql_model = { path = "../sql_model" }

async-dup = "1.2.1"
async-io = "1.1.2"
blocking = "1.0.0"
futures-lite = "1.7.0"
itertools = "0.9.0"
log = "0.4.8"
simple_logger = { version = "1.9.0", default-features = false }
smol = "1.0.0"
sqlparser = { version = "0.6.1", features = ["bigdecimal"] }

[dev-dependencies]
rstest = "0.6.4"
