[package]
name = "node"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[lib]
name = "node"

[[bin]]
name = "database"
path = "src/bin.rs"

[dependencies]
async-trait = "0.1.36"
kernel = { path = "../kernel" }
sql_engine = { path = "../sql_engine" }
sql_types = { path = "../sql_types" }
storage = { path = "../storage" }
smol = "0.1.18"
protocol = { path = "../protocol" }
log = "0.4.8"
simple_logger = { version = "1.6.0", default-features = false }
futures-util = "0.3.5"
async-std = "1.6.2"
async-native-tls = "0.3.3"
