[package]
name = "expr_eval"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
ast = { path = "../ast" }
protocol = { path = "../protocol" }
sql_model = { path = "../sql_model" }
bigdecimal = "0.1.2"
