[package]
name = "sql_types"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
lexical = "5.2.0"
serde = { version = "1.0.114", features = ["derive"] }
protocol = { path = "../protocol" }

[dev-dependencies]
rstest = "0.6.4"
